### PR TITLE
fix(#617) -  Incorrect links and other fixes for beta and qa instances

### LINKED ISSUE #617: Incorrect links and other fixes for beta and qa instances
## Describe the bug 

Screenshot 2020-08-17 at 3 55 51 PM
Screenshot 2020-08-17 at 3 56 12 PM
Screenshot 2020-08-17 at 3 55 27 PM
Screenshot 2020-08-17 at 3 56 26 PM

## Expected behavior

SPAs/Microservices should not be mixed up together

## Environment

- Operating System(s): Linux/macOS/Windows [Variant and Version]
- Browser: Firefox/Chrome/Safari [Version] / Other (please specify)

### PR DESCRIPTION
**Pull request by hybridx**
### Resolves #617 

# Explain the feature/fix

Added the fixes to show SPAs only on the apps in spotlight section

## Does this PR introduce a breaking change

No

## Screenshots

Screenshot 2020-08-17 at 6 24 56 PM

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [x] Does the change have appropriate unit tests?
- [x] Did tests pass?
- [x] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [x] Was this feature demo'd and the design review approved?

### CODE REVIEW

**Comment by sayak-sarkar** [comment]
Descriptive title for the PR please!

File: packages/home-spa/src/js/controller.js [hunk 1]
```diff
@@ -33,7 +33,7 @@ window.OpAuthHelper.onLogin( () => {
       microserviceCard.innerHTML = errorFetchingInformation;
       apps.innerHTML = errorFetchingInformation;
     });
-})
+// });
```
Comment (sayak-sarkar) [inline packages/home-spa/src/js/controller.js:36]: Why the commented lines?

Comment (hybridx) [reply packages/home-spa/src/js/controller.js]: Removed it
